import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import Asidebar from "@/components/Asidebar";

const font = Poppins({ subsets: ["latin"], weight: ["400", "900"] });

export const metadata: Metadata = {
  title: "Responsividade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={font.className}>
        <Asidebar>{children}</Asidebar>
      </body>
    </html>
  );
}
